name: Build and Push Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version (e.g. 1.0.5)'
        required: true

env:
  IMAGE_NAME: scripa01/cloud-app
  VERSION: ${{ github.event.inputs.version }}

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t $IMAGE_NAME:$VERSION .
          docker push $IMAGE_NAME:$VERSION